apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-cloud-deployment-gke-storage
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: storage
    source:
      repo: https://github.com/GoogleCloudPlatform/terraform-cloud-deployment-gke.git
      sourceType: git
      dir: /infra/modules/storage
    actuationTool:
      flavor: Terraform
      version: ">= 0.13"
    description: {}
  content:
    examples:
    - name: simple_example
      location: examples/simple_example
  interfaces:
    variables:
    - name: labels
      description: A map of key/value label pairs to assign to the bucket.
      varType: map(string)
      defaultValue: {}
    - name: location
      description: Bucket location
      varType: string
      defaultValue: null
      required: true
    - name: name
      description: Bucket name
      varType: string
      defaultValue: null
      required: true
    - name: project_id
      description: Google Cloud project ID.
      varType: string
      defaultValue: null
      required: true
    outputs:
    - name: bucket_name
      description: Bucket name
  requirements:
    roles:
    - level: Project
      roles:
      - roles/storage.admin
      - roles/iam.serviceAccountAdmin
      - roles/resourcemanager.projectIamAdmin
      - roles/editor
      - roles/datastore.owner
    services:
    - cloudresourcemanager.googleapis.com
    - iam.googleapis.com
    - storage.googleapis.com
    - serviceusage.googleapis.com
